
services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5435:5432"
    container_name: postgres-inventory
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-service
      - PGDATA=/data/postgres
    volumes:
      - ./data/inventory:/var/lib/postgresql/data
      - ./init/inventory/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8887:80"
    container_name: pgadmin-inventory
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ca
      - PGADMIN_DEFAULT_PASSWORD=password
